 language: node_js
 node_js:
   - "0.10"
 before_script:
   - "echo start of before script"
   - "echo We use the config example as the config this must happen before migration"
   - cp ./config-example.js ./config.js
   - "echo create database blobvault as user postgres"
   - psql -c 'create database blobvault;' -U postgres
   - "echo make test script executable"
   - chmod +x test.sh
   - "echo End of before script"
